config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "lists#index"
  resources :lists do
  resources :bookmarks
end

resources :movies

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    before_action :set_list
    before_action :set_bookmark, only: [:edit, :update, :show, :destroy]
    
    def index
        @bookmarks = Bookmark.all
      end
    
      def show;  end

      def edit; end
    
      def new
        @bookmark = Bookmark.new
      end
    
      def create
        @bookmark = Bookmark.new(bookmark_params)
        @bookmark.list = @list
        if @bookmark.save
          redirect_to list_path(@list)
        else
          render :new
        end
      end

      def destroy
        @bookmark = List.bookmark.find(params[:id])
        @bookmark.destroy
        redirect_to list_path
      end
    
      private
    
      def set_list
        @list = List.find(params[:list_id])
      end
    
      def set_bookmark
        @bookmark = Bookmark.find(params[:id])
      end
    
      def bookmark_params
        params.require(:bookmark).permit(:comment, :movie_id, :list_id)
      end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    before_action :set_list, only: [:show, :edit, :update, :destroy]


    def index
        @lists = List.all
    end


    def show; end

  def new
    @lists = List.new
  end

  def create
    @lists = List.new(lists_params)
    @lists.save

    redirect_to lists_path(@lists)
  end

  def edit; end

  def update
    @lists.update(lists_params)

    redirect_to lists_path(@lists)
  end

  def destroy
    @lists = List.bookmark.find(params[:id])
    @lists.destroy

    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def lists_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movies, only: [:show, :edit, :update, :destroy]

    def index
        @movies = Movie.all
    end

    def show; end

  def new
    @movies = Movie.new
  end

  def create
    @movies = Movie.new(movies_params)
    @movies.save

    redirect_to movies_path(@movies)
  end

  def edit; end

  def update
    @movies.update(movies_params)

    redirect_to movies_path(@movies)
  end

  def destroy
    @movies.destroy

    redirect_to movies_path
  end

  private

  def set_movies
    @movies = Movie.find(params[:id])
  end

  def movies_params
    params.require(:movies).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.label :Comment %>
  <%= f.input :comment, label: false %>
  <%= f.label :Movie %>
  <%= f.association :movie, label: false %>
  <%= f.submit class: 'btn btn-success rounded-pill mt-3' %>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="container">

    <div class="row justify-content-center">
        <div class="col-sm-12 col-lg-3">
            <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment %>
            <%= f.association :movie %>
            <%= f.submit class: 'btn btn-success rounded-pill mt-3' %>
            <% end %>

            <p><%= link_to "Delete bookmark", list_bookmark_path(@bookmark), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger rounded-pill mt-2" %></p>
        </div>
    </div>


</div>

app/views/bookmarks/new.html.erb
 
<div class="container mt-5">
  <%= link_to "Back", list_path(@list), class: "btn btn-secondary rounded-pill" %>
    <div class="">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-4  right-bg justify-content-center text-center align-items-center border p-5" style="border-radius: 20px;" >
          <%= render 'form', bookmark: @bookmark %>
        </div>
      </div>
    </div>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@lists) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-success mt-3' %>
  <%= f.button :button, 'Back', type: :back, class: 'btn btn-danger mt-3' %>
<% end %>

app/views/lists/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>My Movies Lists</h1>
        <p class="text-center" style="margin-top: 10px;">Exercise created during the Bootcamp at Le wagon Lisbon.</p>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="container">

  <div class="">
    <div class="row align-items-start">
    <div class="col-lg-6" >
    <h1>Edit List</h1>
    <br>
      <%= render 'form', list: @lists %>
   </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render 'header' %>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-10">

      <div class="mt-3 text-center">
        <p><%= link_to "Create new List",  new_list_path(@list), class: "btn btn-success rounded-pill" %></p>
      </div>
    </div> 
  </div>

  <div class="row mt-5">
    <% @lists.each do |list| %> 
      <div class="col-sm-12 col-lg-2 p-2">
        <%= link_to list_path(list) do %>
          <div class="btn-blue btn-primary">
            <div class="d-flex align-items-center"  style="height: 100%;">
              <h5 class="mt-2 ms-4"><%= list.name %><i class="fas fa-play ms-3"></i></h5>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="footer mt-2">
    <div class="footer-links" style="margin-top: 210px;">
      <a href="https://github.com/rodrigonobrega1" target="_blank"><i class="fab fa-github" style="color: white;"></i></a>
      <a href="https://www.instagram.com/rodrigonobrega1/"><i class="fab fa-instagram" target="_blank" style="color: white;"></i></a>
      <a href="https://www.facebook.com/rodrigo.nobrega.90/"><i class="fab fa-facebook" target="_blank" style="color: white;"></i></a>
      <a href="https://www.linkedin.com/in/rodrigonobrega1/"><i class="fab fa-linkedin" target="_blank" style="color: white;"></i></a>
    </div>
    <div class="footer-copyright">
      Rodrigo Nobrega - Fullstack Web developer and Outsystems Web developer
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">

  <div class="">
    <div class="row align-items-start">
    <div class="col-lg-6" >
    <h1>Create New List</h1>
    <br>
      <%= render 'form', list: @lists %>
   </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="col-sm-12 col-lg-12">
    <h2 class="text-center mt-5"> <%= @list.name %> Movies</h2>
    <p><%= link_to "Back to Home", lists_path, class:"btn btn-secondary rounded-pill"%></p>
  </div>
</div>

<div class="container text-center">
    <p><%= link_to "Bookmark",  new_list_bookmark_path(@list), class: "btn btn-success rounded-pill" %></p>
</div>

<div class="container">
  <div class="row justify-content-center">
    <% @list.movies.each do |movie| %>
      <div class="col-sm-12 col-lg-3">
        <div class="border p-4 text-center" style="border-radius: 20px; width: 300px; height: 100%">
          <img class="img-poster" src="<%= movie.poster_url %>">
          <h6><%= movie.title %> - <%= movie.rating %><i class="ms-2 fas fa-star" style="color: gold;"></i></h6>
          <p class="p-2" style="color: grey;"><%= movie.overview %></p>
          <div class="text-center"style="position: absolute; bottom: 0;">
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<h1>My Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.title, movies_path(movie) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add movie", movie_path(@movie) %>

app/views/movies/new.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn-submit-movie mt-3' %>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movies.title %> - <%= @movies.rating %></h1>
<br>
<h6><%= @movies.overview %></h6>
<br>
<p><%= @movies.poster_url %></p>
<%= link_to "Delete", movies_path(@movies) %>
<%= link_to "Back", :back %>